//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.Permission = new HashSet<Permission>();
            this.UserLevelPermission = new HashSet<UserLevelPermission>();
        }
    
        public int ID { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string PageUrl { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsVisibleOnMenu { get; set; }
        public Nullable<bool> HasSubNodeOnMenu { get; set; }
        public string MenuIcon { get; set; }
        public Nullable<bool> IsAuthorized { get; set; }
        public Nullable<int> ParentRankNumber { get; set; }
        public Nullable<int> RankNumber { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> MenuItemLevel { get; set; }
        public Nullable<bool> HasExecutePermission { get; set; }
        public Nullable<bool> HasViewPermission { get; set; }
        public Nullable<bool> HasAddPermission { get; set; }
        public Nullable<bool> HasUpdatePermission { get; set; }
        public Nullable<bool> HasDeletePermission { get; set; }
        public Nullable<bool> HasSearchPermission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLevelPermission> UserLevelPermission { get; set; }
    }
}
