//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESLER
    {
        public int ID { get; set; }
        public int FIRMA_ID { get; set; }
        public Nullable<int> TIP { get; set; }
        public Nullable<int> ULKE { get; set; }
        public Nullable<int> SEHIR { get; set; }
        public string POSTA_KODU { get; set; }
        public string ADRES { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public bool IsDefaultForB2b { get; set; }
    
        public virtual AdresTipi AdresTipi { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
        public virtual ULKELER ULKELER { get; set; }
        public virtual SEHIRLER SEHIRLER { get; set; }
    }
}
