//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelUploadLog
    {
        public int ID { get; set; }
        public string ExcelUploadEntity { get; set; }
        public Nullable<System.Guid> FirmID { get; set; }
        public Nullable<int> TransferedRowCount { get; set; }
        public Nullable<int> TotalRowCount { get; set; }
        public Nullable<bool> HasError { get; set; }
        public string ErrorText { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.DateTime> CompletionDT { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Member Member { get; set; }
    }
}
