//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public Nullable<int> FromMemberID { get; set; }
        public Nullable<int> ToMemberID { get; set; }
        public string Text { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> DetectionID { get; set; }
        public Nullable<bool> IsDeletedForSent { get; set; }
        public Nullable<System.DateTime> DeletedOnForSent { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual Detection Detection { get; set; }
    }
}
