//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDetay
    {
        public int NumID { get; set; }
        public string IrsaliyeNo { get; set; }
        public string CustomerCode { get; set; }
        public string BuCode { get; set; }
        public string NAME_EN { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Updates { get; set; }
        public string UpdatesUser { get; set; }
    }
}
