//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeroX
    {
        public int TPID { get; set; }
        public string BUKOD { get; set; }
        public string XPSUP { get; set; }
        public string XPSNO { get; set; }
        public string NAME { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_DE { get; set; }
        public string OEM { get; set; }
        public string RAKIPTAD { get; set; }
        public string RAKIPTNO { get; set; }
        public string RAKIPTAD1 { get; set; }
        public string RAKIPTNO1 { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public Nullable<System.DateTime> ADDED { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string MARKA { get; set; }
    }
}
