//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODetay
    {
        public int ORDID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderNO { get; set; }
        public string CustomerCode { get; set; }
        public string BuCode { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string BUESKI { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_DE { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> TerminDate { get; set; }
        public Nullable<System.DateTime> Updates { get; set; }
        public string UpdatesUser { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
