//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPLog
    {
        public System.Guid ID { get; set; }
        public string UserID { get; set; }
        public string GsmNumber { get; set; }
        public Nullable<int> ProcessTypeID { get; set; }
        public Nullable<System.Guid> EntityID { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> ExpiringTime { get; set; }
        public string OTPPassword { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.Guid> VerifiedID { get; set; }
    }
}
