//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.MPRODUCTS = new HashSet<MPRODUCTS>();
            this.ODetay = new HashSet<ODetay>();
            this.OEM = new HashSet<OEM>();
            this.ProductImage = new HashSet<ProductImage>();
            this.TEKLIFLER_DETAY = new HashSet<TEKLIFLER_DETAY>();
            this.TPRODUCTS = new HashSet<TPRODUCTS>();
            this.RelatedProduct = new HashSet<RelatedProduct>();
            this.RelatedProduct1 = new HashSet<RelatedProduct>();
            this.ProductBundle = new HashSet<ProductBundle>();
            this.ProductBundle1 = new HashSet<ProductBundle>();
        }
    
        public int PRODID { get; set; }
        public string BUKOD { get; set; }
        public Nullable<int> SECID { get; set; }
        public Nullable<int> MCATID { get; set; }
        public Nullable<int> CATID { get; set; }
        public string NAME { get; set; }
        public string MARKA { get; set; }
        public string DESI { get; set; }
        public Nullable<System.DateTime> ADDED { get; set; }
        public string ADDEDBY { get; set; }
        public string RESIM { get; set; }
        public string TRESIM { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public string EDITOR_TABLE { get; set; }
        public string EDITOR_TABLE_EN { get; set; }
        public string EDITOR_TABLE_GR { get; set; }
        public string EDITOR_TABLE_FR { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_DE { get; set; }
        public string NAME_FR { get; set; }
        public Nullable<int> SIRALAMA { get; set; }
        public string DESCC { get; set; }
        public string CATGROUP { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<decimal> B2BBasePrice { get; set; }
        public Nullable<int> B2BCurrencyID { get; set; }
        public Nullable<bool> OpenForSale { get; set; }
        public Nullable<decimal> PackagePieceCount { get; set; }
        public string PackageDimensions { get; set; }
        public Nullable<decimal> CountInPalette { get; set; }
        public Nullable<bool> IsEuroPalette { get; set; }
        public Nullable<bool> B2BIsVisible { get; set; }
        public Nullable<bool> B2BIsVisibleOnHomepage { get; set; }
        public Nullable<bool> B2BIsVisibleOnCategoryHomepage { get; set; }
        public Nullable<bool> B2BIsNewProduct { get; set; }
        public Nullable<bool> B2BIsOnSale { get; set; }
        public Nullable<decimal> B2BDiscountedPrice { get; set; }
        public string EDITOR_B2B { get; set; }
        public string EDITOR_ManagerNote { get; set; }
        public Nullable<decimal> B2BStockAmount { get; set; }
        public Nullable<bool> IsBundled { get; set; }
        public string BUKOD2 { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual MAINCATEGORIES MAINCATEGORIES { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRODUCTS> MPRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODetay> ODetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OEM> OEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEKLIFLER_DETAY> TEKLIFLER_DETAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPRODUCTS> TPRODUCTS { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedProduct> RelatedProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedProduct> RelatedProduct1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBundle> ProductBundle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBundle> ProductBundle1 { get; set; }
        public virtual SECTIONS SECTIONS { get; set; }
    }
}
