//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEKLIFLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEKLIFLER()
        {
            this.TEKLIFLER_DETAY = new HashSet<TEKLIFLER_DETAY>();
        }
    
        public int TID { get; set; }
        public string TEKLIFNO { get; set; }
        public Nullable<int> TTIPI { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public string CustomerID { get; set; }
        public string FIRMPID { get; set; }
        public Nullable<int> YetkiliKisiID { get; set; }
        public string TITLE { get; set; }
        public string ICERIK { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public int TDURUMU { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEKLIFLER_DETAY> TEKLIFLER_DETAY { get; set; }
        public virtual TeklifDurumu TeklifDurumu { get; set; }
        public virtual TeklifTipi TeklifTipi { get; set; }
        public virtual YETKILI_KISILER YETKILI_KISILER { get; set; }
    }
}
