//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenLog
    {
        public string ID { get; set; }
        public string sid { get; set; }
        public string userid { get; set; }
        public Nullable<System.Guid> firmid { get; set; }
        public string donemid { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> FinishedOn { get; set; }
        public Nullable<int> SentSMSCount { get; set; }
        public Nullable<int> SentMailCount { get; set; }
        public Nullable<int> ToSignPDFCount { get; set; }
        public Nullable<int> SignedPDFCount { get; set; }
    }
}
