//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToplantiMember
    {
        public int ID { get; set; }
        public Nullable<int> ToplantiID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> AssignedOn { get; set; }
        public string AssignedBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual TOPLANTILAR TOPLANTILAR { get; set; }
    }
}
