//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPLANTILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOPLANTILAR()
        {
            this.ToplantiMember = new HashSet<ToplantiMember>();
            this.ToplantiYetkiliKisi = new HashSet<ToplantiYetkiliKisi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TIP { get; set; }
        public string PERSON_ID { get; set; }
        public int FIRMID { get; set; }
        public System.DateTime TARIH { get; set; }
        public string TITLE { get; set; }
        public string ICERIK { get; set; }
        public int SEBEP { get; set; }
        public string FIRMPERSON { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual ToplantiSebep ToplantiSebep { get; set; }
        public virtual ToplantiTipi ToplantiTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToplantiMember> ToplantiMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToplantiYetkiliKisi> ToplantiYetkiliKisi { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
    }
}
