//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProductsLog
    {
        public System.Guid ID { get; set; }
        public string LogType { get; set; }
        public int TPID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string BUKOD { get; set; }
        public string XPSUP { get; set; }
        public string XPSNO { get; set; }
        public string NAME { get; set; }
        public string OEM { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public string BRAND { get; set; }
        public string EDITOR_TABLE { get; set; }
        public string NAME_DE { get; set; }
        public string NAME_EN { get; set; }
        public string XPSUPNO { get; set; }
        public Nullable<System.DateTime> ADDED { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string UpdatedBy { get; set; }
        public string CATNAME { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual Currency Currency1 { get; set; }
    }
}
