//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nero2021.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKILI_KISILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YETKILI_KISILER()
        {
            this.Orders = new HashSet<Orders>();
            this.TEKLIFLER = new HashSet<TEKLIFLER>();
            this.ToplantiYetkiliKisi = new HashSet<ToplantiYetkiliKisi>();
        }
    
        public int ID { get; set; }
        public int FIRMA_ID { get; set; }
        public string GOREV { get; set; }
        public Nullable<int> ContactTitleID { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
        public string MAIL_ADRESI { get; set; }
        public string GSM { get; set; }
        public string TEL { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<bool> IsB2bUser { get; set; }
        public string B2bUsername { get; set; }
        public string B2bPassword { get; set; }
    
        public virtual ContactTitle ContactTitle { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEKLIFLER> TEKLIFLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToplantiYetkiliKisi> ToplantiYetkiliKisi { get; set; }
    }
}
